### ISSUE TITLE
Doc - relative links such as contribution guide links not working on community membership page

### ISSUE THREAD

**Issue by faraggi** [PegaSysEng/pantheon#1162]
### Description
As a prospective pantheon community member, I want to access the contributing guide from the current docs.

### Steps to Reproduce (Bug)
1. Go to https://docs.pantheon.pegasys.tech/en/stable/community/community-membership/#new-contributors
2. Click on the 'New Contributors' link or the 'contributor guide' link.

**Expected behavior:**
Link should go to contribution guidelines: 
https://github.com/PegaSysEng/pantheon/blob/master/CONTRIBUTING.md

**Actual behavior:**
Link directs to a 404 page 
https://docs.pantheon.pegasys.tech/CONTRIBUTING.md

### Additional Information
Replace relative links like these:
`[contributor guide]: /CONTRIBUTING.md`
`[New contributors]: /CONTRIBUTING.md`
`[CLA.md]: /CLA.md`
`[code reviews]: ./code-reviews.md`

With their corresponding absolute links: 
''' https://github.com/PegaSysEng/pantheon/blob/master/CONTRIBUTING.md '''
''' https://github.com/PegaSysEng/pantheon/blob/master/CLA.md '''
"./code-reviews.md"

(or with a relative link but I can't seem to get it to work with relative links directing to the root folder on my local machine.)

**Comment by NicolasMassart** [comment]
This is more than a link issue. The .md files you are referring are not meant to be viewed in the doc site context. The architecture, community and development directories are here because they were not moved from the docs directory when we put the doc site in place. But they should. This requires a more global thinking about these contents and if we decide to add them in the doc site. Otherwise they should be moved out of the docs directory. Also, are they still up to date and not duplicated elsewhere ? We have to go through this checks before just changing the links IMO.

**Comment by faraggi** [comment]
I see, I wasn't aware of these subtleties.
I believe I arrived there by opening the file in the docs folder, because the docs menu doesn't navigate there.
Thanks for the reply.

**Comment by NicolasMassart** [comment]
Even if you came from an unofficial path, it should work. So we have to decide what to do with these pages. Include trhem properly in doc site or completely move them out of it.

**Comment by arash009** [comment]
Closing this issue and moving ticket to [Jira](https://pegasys1.atlassian.net/browse/PAN-2507) for tracking.
