### ISSUE TITLE
Document permissioning for submitting transactions 

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#458]
### Description
As a user, I want documentation how to define role level permissions for submitting transactions.

### Acceptance Criteria
* Document how to define role level permissions for submitting transactions.
* Update Permissioning overview (#457) documentation to reference this documentation 
* Documentation tested

**Comment by donntrenton** [comment]
Blocked as there's currently no info on this. Asked priv-pegasys-prod-dev channel on Slack about Groups and Roles permissioning:

I'm working on an issue (#458) to document role-level permissions; I read the Pantheon EEA Permissioning Design Document, but there's no information in the Groups and Roles section. Do we plan to support this for 1.0 and have we implemented any CLI options or methods for it?

**Comment by donntrenton** [comment]
Following up to investigate.

From priv-pegasys-prod-dev on 2019-01-10:

[Donn:]
I'm working on an issue (#458) to document role-level permissions; I read the Pantheon EEA Permissioning Design Document, but there's no information in the Groups and Roles section. Do we plan to support this for 1.0 and have we implemented any CLI options or methods for it?

[Arash Mahboubi:]
Roles and Groups as a concept doesnt exist yet. This is part of work for post 1.0 release. The current role-level permissions use an account.
This ticket is about accepting a transaction from certain accounts that are on a whitelist.

[Donn:]
Thanks for clearing that up. So it looks like instead this issue is asking for a conceptual explanation of using --accounts_whitelist.

**Comment by MadelineMurray** [comment]
https://github.com/PegaSysEng/pantheon/pull/460 is the dev work for this. 

--accounts-whitelisting was added to the doc by #505 
Conceptual content will be added by #457 

Closing this one.
